### ISSUE TITLE
Make qvm-ls-mermaid installable to a admin qube?

### ISSUE THREAD

**Issue by ddevz** [3hhh/qvm-ls-mermaid#1]
This is cool.  If it didn't have to install to dom0, I bet more people would use this.  Have you seen the Qubes Admin API?  ( https://www.qubes-os.org/doc/admin-api/ ).  

It seems to me like if someone sets up a admin qube as shown in: https://www.qubes-os.org/news/2017/06/27/qubes-admin-api/  (configuring it to give read-only access for qvm-ls command and others), and then did a git clone in that qube of qvm-ls-mermaid and blib, then would qvm-ls-mermaid be able to be adjusted to be able to run in that qube?

on the qube setup side:
admin.vm.List would need to be granted
admin.vm.property.Get would need to be granted
for qvm-ls

and for qrexec-policy-graph it would probably need at least policy.List

**I gave it a try, doing something like the following:**  

```
qvm-run debian-11 'sudo apt update'
qvm-run debian-11 'sudo apt install qubes-core-admin-client qubes-manager'
qvm-shutdown debian-11

qvm-create --template debian-11 --property netvm=sys-firewall-internet --label gray sys-admin-mermaid


qvm-run --pass-io  sys-admin-mermaid 'git clone --recurse-submodules https://github.com/3hhh/qvm-ls-mermaid.git'
qvm-run --pass-io  sys-admin-mermaid 'git clone --recurse-submodules https://github.com/3hhh/blib.git'

qvm-prefs sys-admin-mermaid netvm none


###bypass dependancy checks:  this will dissapear after reboot
qvm-run --pass-io  sys-admin-mermaid 'sudo ln -s /usr/sbin/losetup /usr/local/bin/'
qvm-run --pass-io  sys-admin-mermaid 'sudo ln -s /usr/bin/qvm-device /usr/bin/qvm-block'
qvm-run --pass-io  sys-admin-mermaid 'cd ~/blib/; sudo ./installer install'


sudo sh -c 'echo "sys-admin-mermaid \$adminvm allow,target=\$adminvm
sys-admin-mermaid \$anyvm allow,target=\$adminvm" > /etc/qubes-rpc/policy/admin.vm.List'

sudo cp /etc/qubes-rpc/policy/admin.vm.List  /etc/qubes-rpc/policy/admin.vm.property.Get
sudo cp /etc/qubes-rpc/policy/admin.vm.List  /etc/qubes-rpc/policy/admin.vm.property.GetAll
sudo cp /etc/qubes-rpc/policy/admin.vm.List  /etc/qubes-rpc/policy/admin.property.List
sudo cp /etc/qubes-rpc/policy/admin.vm.List  /etc/qubes-rpc/policy/admin.property.Get
sudo cp /etc/qubes-rpc/policy/admin.vm.List  /etc/qubes-rpc/policy/admin.property.GetAll
```

Then trying to run it in the sys-admin-mermaid qube with: 
`./qvm-ls-mermaid --browser firefox sys-admin-mermaid `

(I.E. trying to get it to display it via its own qube)

I get: 
`INFO: Generated the mermaid output. Ensuring that the sys-admin-mermaid target VM is running...
`
But then get:
```
ERROR: Not running: sys-admin-mermaid Stack Trace:
(/usr/lib/blib/lib/os/qubes4/dom0:688) b_defaultErrorHandler
  (/usr/lib/blib/lib/os/qubes4/dom0:698) blib_dom0_checkRunningMultiple
    (./qvm-ls-mermaid:537) b_dom0_ensureRunning
      (./qvm-ls-mermaid:555) main Aborting...
```
and some permission errors from dom0 (probably doing the policy wrong for giving it access to check the current state of itself)

I can't tell if it's not generating the file properly, or its writing the file somewhere properly and just not copying it to itself successfully.

Does it write the file to a temporary file before trying to copy it to itself?   I can't seem to find a /tmp/qvm-ls-mermaid directory which i thought might be it.

Also, note that losetup is unlikely to be useful from inside the admin qube (if it is actually used in the basic report)

Also, I'm not sure what the output file should even look like as i dont see .html anywhere.  (maybe it launches a web browser directly on a .js file?)

**Comment by 3hhh** [comment]
On 12/18/23 22:52, ddevz wrote:
> But then get:
> ```
> ERROR: Not running: sys-admin-mermaid Stack Trace:
> (/usr/lib/blib/lib/os/qubes4/dom0:688) b_defaultErrorHandler
>    (/usr/lib/blib/lib/os/qubes4/dom0:698) blib_dom0_checkRunningMultiple
>      (./qvm-ls-mermaid:537) b_dom0_ensureRunning
>        (./qvm-ls-mermaid:555) main Aborting...
> ```
> and some permission errors.

The script attempts to start a target VM where to copy the output and run the browser. That probably wasn't allowed by your policy.
Maybe it works, if you try with `dom0` (= local print) as output VM, idk.

Anyway I just added some steps that describe how to run it outside of dom0 without modifying the policy.
Probably one could write a short script to do that in dom0, but that's essentially just replicating what `qvm-ls-mermaid` does in dom0 imho... ;-)

**Comment by ddevz** [comment]
Thanks!  I'm trying it out.  

> Probably one could write a short script to do that in dom0, but that's essentially just replicating what `qvm-ls-mermaid` does in dom0 imho... ;-)

I was thinking the same thing as I was writing my dom0 steps above!  heh
There is a important difference though.  They seem actively excited about admin policies right now, so getting them to security review some policies would probably be much easier  then getting them to security review qvm-ls-mermaid and blib if we wanted to get it included in qubes proper.

I'll let you know how it goes.

I encountered a "syntax error ", but i'll put that in it's own issue

**Comment by ddevz** [comment]
First off, I want to mention that you seem to have a excessive amount of bash scripting knowledge :)  

Now the actual comment: 
Any chance that the --vm option could optionally be made to run commands (for example the `qvm-ls --raw-data -O name,CLASS,label,netvm,provides_network,template,template_for_dispvms,virt_mode > qvmls.txt && qrexec-policy-graph --include-ask` command) in the local vm ( for those that do want to set up their policies)?  Like maybe detect if there is no input piped into it?  or maybe a separate flag?

I ask because if i comment out the section at the end of this comment, then the following actually works in the vm:
```
./qvm-ls-mermaid 
{wait for "no such domain:" error}
cd mermaid
./run
```

(Note: ./qvm-ls-mermaid -R does not work yet in the VM because of  `qrexec-policy-graph --include-ask` permissions but I'm hoping to get it working)


**The section I commented out to get it to generate the file:**
```
b_info "Generated the mermaid output. Ensuring that the ${outVM:-"disposable"} 
target VM is running..."
if [ -z "$outVM" ] ; then
  outVM="$(b_dom0_startDispVM)" || { B_ERR="Failed to start a disposable VM." ;
 B_E ; }
else
  b_dom0_ensureRunning "$outVM"
fi
```

**Comment by 3hhh** [comment]
So you're still trying to get it working from the admin VM?

I just noticed that these VMs have the dom0 `qvm-` tools locally installed as well - I wasn't aware of that as I never used one.

Then your original approach without `--vm` should work imo.

However you should try `./qvm-ls-mermaid dom0` for local output (print only). I never designed `qvm-ls-mermaid` to display anything except for printing anything in the local VM/dom0 as I don't trust that `mermaid-js` code and at least in dom0 there shouldn't be a browser anyway. You can use `run` manually though.

If you want it to display in a different VM, grant your admin VM full access (most importantly execute access) to that VM and run `./qvm-ls-mermaid --browser firefox vm`.

**Comment by ddevz** [comment]
I get it!  The dom0 output is the same as in qvm-ls-mermaid.js !   (I had tried `./qvm-ls-mermaid dom0` after you first mentioned it, but at the time I thought I was expected to visually parse the output instead of looking at the graph (I had never seen a qvm-ls-mermaid.js file at that time as it was halting before the file got generated).)

So in other words,  I can just:
```
./qvm-ls-mermaid dom0 > mermaid/qvm-ls-mermaid.js
cd mermaid/
./run
```

(I just tested it and it does work)


> I just noticed that these VMs have the dom0 `qvm-` tools locally installed as well - I wasn't aware of that as I never used one.

Ya, that's what the:
```
qvm-run debian-11 'sudo apt update'
qvm-run debian-11 'sudo apt install qubes-core-admin-client qubes-manager'
qvm-shutdown debian-11

```
part was for. :)

Thanks for your help

**Comment by 3hhh** [comment]
On 12/22/23 18:25, ddevz wrote:
> So in other words,  I can just:
> ```
> ./qvm-ls-mermaid dom0 > mermaid/qvm-ls-mermaid.js
> cd mermaid/
> ./run
> ```
> 
> (I just tested it and it does work)

Exactly. Glad to hear you got it working. :-)

**Comment by ddevz** [comment]
Note: I posted instructions for qvm-ls-mermaid in a admin qube on the qubes forum under "Community Guides"

**Comment by 3hhh** [comment]
On 12/24/23 23:17, ddevz wrote:
> Note: I posted instructions for qvm-ls-mermaid in a admin qube on the qubes forum under "Community Guides"

Yes, I noticed that. You can find the link in my updated README. ;)
