### ISSUE TITLE
Web page says "syntax error"

### ISSUE THREAD

**Issue by ddevz** [3hhh/qvm-ls-mermaid#2]
It appears that having a qube that has a "--" (double dash) in its name seems to cause a "syntax error" message to show in the web browser instead of showing the graph.

(And since spaces are not allowed in names, double dash becomes increasing likely as the number of qubes on one system get higher).

I'm guessing this is probably a constraint of mermaid.  Since the output is visual, and can't be piped into anything, perhaps something like:

`| sed 's/--/-/' |`

would be livable?

**Comment by 3hhh** [comment]
Yes. Good catch!
